font_family      Noto Sans Mono
font_size        11.0
enable_audio_bell no
confirm_os_window_close 0
window_padding_width 8
background_opacity 0.96
background #1e1e2e
foreground #cdd6f4
selection_background #585b70
selection_foreground #cdd6f4
cursor #f5e0dc
url_color #89b4fa
shell fish
