shell fish
font_family FiraCode Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13.0
disable_ligatures never

window_padding_width 8
background_opacity 0.96
dynamic_background_opacity yes
confirm_os_window_close 0
enable_audio_bell no

foreground #cdd6f4
background #1e1e2e
selection_foreground #cdd6f4
selection_background #585b70
cursor #f5e0dc
url_color #89b4fa

# DMS/Matugen 会更新这两个文件；主配置保留字体和 Fish 设置。
include dank-tabs.conf
include dank-theme.conf
include arch-niri-terminal.conf
